# Generated by Django 3.0.5 on 2020-04-24 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSWLP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/about_swlp')),
                ('image_alt_txt', models.CharField(blank=True, max_length=100)),
                ('image_heading', models.CharField(max_length=100)),
                ('image_description', models.TextField()),
                ('image_button_text', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'AboutSWLP',
            },
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/blogs/')),
                ('image_alt_txt', models.CharField(blank=True, max_length=100)),
                ('heading', models.CharField(default='Blog Heading goes here ', max_length=100)),
                ('summary', models.TextField(default='Blog Summary goes here', max_length=150)),
                ('content', models.TextField(default='Blog Content goes here', max_length=5000)),
                ('author', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Blogs',
            },
        ),
        migrations.CreateModel(
            name='BlogSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=5000)),
            ],
            options={
                'verbose_name_plural': 'BlogSection',
            },
        ),
        migrations.CreateModel(
            name='BoardTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/board/')),
                ('image_alt_txt', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'BoardTeam',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/gallery')),
                ('image_alt_txt', models.CharField(blank=True, max_length=100)),
                ('tag', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Gallery',
            },
        ),
        migrations.CreateModel(
            name='JoinUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('button_text', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'JoinUs',
            },
        ),
        migrations.CreateModel(
            name='LeaderSaysSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=5000)),
            ],
            options={
                'verbose_name_plural': 'LeaderSaysSection',
            },
        ),
        migrations.CreateModel(
            name='OrganizingTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/organizing/')),
                ('image_alt_txt', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'OrganizingTeam',
            },
        ),
        migrations.CreateModel(
            name='OurCauses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/our_causes')),
                ('image_alt_txt', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OurChildrensSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'OurChildrensSection',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=100)),
                ('image', models.ImageField(default='', upload_to='images/slider/')),
                ('image_alt_txt', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Slider',
            },
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('less', models.TextField(default='')),
                ('more', models.TextField(default='')),
            ],
            options={
                'verbose_name_plural': 'Vision',
            },
        ),
        migrations.CreateModel(
            name='VisionIcons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=30)),
                ('icon_name', models.CharField(max_length=50)),
                ('icon_description', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Vision')),
            ],
            options={
                'verbose_name_plural': 'VisionIcons',
            },
        ),
        migrations.CreateModel(
            name='OurChildrens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/our_childrens/')),
                ('image_alt_txt', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=5000)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.OurChildrensSection')),
            ],
            options={
                'verbose_name_plural': 'OurChildrens',
            },
        ),
        migrations.CreateModel(
            name='LeaderSays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/leaders/')),
                ('image_alt_txt', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.LeaderSaysSection')),
            ],
            options={
                'verbose_name_plural': 'LeaderSays',
            },
        ),
        migrations.CreateModel(
            name='AboutSWLPIcons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='about_swlp/icons/')),
                ('image_alt_txt', models.CharField(blank=True, max_length=100)),
                ('icon_text', models.CharField(max_length=50)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.AboutSWLP')),
            ],
            options={
                'verbose_name_plural': 'AboutSWLPIcons',
            },
        ),
    ]
