# Generated by Django 3.0.5 on 2020-04-11 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_SWLP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=5000)),
                ('image', models.ImageField(upload_to='about_swlp/image')),
                ('image_heading', models.CharField(max_length=100)),
                ('image_description', models.CharField(max_length=2000)),
                ('image_button_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Blog_section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Board_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='board/')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Join_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=5000)),
                ('button_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Leader_says_section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Organizing_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='organizing/')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Our_childrens_section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=5000)),
                ('image', models.ImageField(upload_to='slider/')),
                ('button_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Vision_icons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='vision-icons/')),
                ('icon_name', models.CharField(max_length=50)),
                ('icon_description', models.CharField(max_length=2000)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Vision')),
            ],
        ),
        migrations.CreateModel(
            name='Our_childrens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='our_childrens/')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=5000)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Our_childrens_section')),
            ],
        ),
        migrations.CreateModel(
            name='Leader_says',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='leaders/')),
                ('name', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=5000)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Leader_says_section')),
            ],
        ),
        migrations.CreateModel(
            name='Health_events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/health/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Events')),
            ],
        ),
        migrations.CreateModel(
            name='Environment_events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/env/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Events')),
            ],
        ),
        migrations.CreateModel(
            name='Empowerment_events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/emp/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Events')),
            ],
        ),
        migrations.CreateModel(
            name='Elderly_events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/elderly/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Events')),
            ],
        ),
        migrations.CreateModel(
            name='Children_events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/child/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Events')),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blogs/')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=5000)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Blog_section')),
            ],
        ),
        migrations.CreateModel(
            name='All_events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/all/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Events')),
            ],
        ),
        migrations.CreateModel(
            name='About_SWLP_icons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='about_swlp/icons/')),
                ('icon_text', models.CharField(max_length=50)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.About_SWLP')),
            ],
        ),
    ]
