# Generated by Django 3.0.5 on 2020-04-12 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSWLP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/about_swlp')),
                ('image_heading', models.CharField(max_length=100)),
                ('image_description', models.TextField()),
                ('image_button_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AboutSWLPIcons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='about_swlp/icons/')),
                ('icon_text', models.CharField(max_length=50)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.AboutSWLP')),
            ],
        ),
        migrations.CreateModel(
            name='AllEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/events/all/')),
            ],
        ),
        migrations.CreateModel(
            name='BlogSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='BoardTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/board/')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ChildrenEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/events/child/')),
            ],
        ),
        migrations.CreateModel(
            name='ElderlyEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/events/elderly/')),
            ],
        ),
        migrations.CreateModel(
            name='EmpowermentEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/events/emp/')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/events/env/')),
            ],
        ),
        migrations.CreateModel(
            name='HealthEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/events/health/')),
            ],
        ),
        migrations.CreateModel(
            name='JoinUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('button_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LeaderSays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/leaders/')),
                ('name', models.CharField(max_length=50)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OrganizingTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/organizing/')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OurChildrens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/our_childrens/')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='OurChildrensSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VisionIcons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='images/vision-icons/')),
                ('icon_name', models.CharField(max_length=50)),
                ('icon_description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='about_swlp_icons',
            name='about',
        ),
        migrations.RemoveField(
            model_name='all_events',
            name='section',
        ),
        migrations.DeleteModel(
            name='Board_team',
        ),
        migrations.RemoveField(
            model_name='children_events',
            name='section',
        ),
        migrations.RemoveField(
            model_name='elderly_events',
            name='section',
        ),
        migrations.RemoveField(
            model_name='empowerment_events',
            name='section',
        ),
        migrations.RemoveField(
            model_name='environment_events',
            name='section',
        ),
        migrations.RemoveField(
            model_name='health_events',
            name='section',
        ),
        migrations.DeleteModel(
            name='Join_us',
        ),
        migrations.RemoveField(
            model_name='leader_says',
            name='section',
        ),
        migrations.DeleteModel(
            name='Organizing_team',
        ),
        migrations.RemoveField(
            model_name='our_childrens',
            name='section',
        ),
        migrations.RemoveField(
            model_name='vision_icons',
            name='section',
        ),
        migrations.AlterField(
            model_name='blogs',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.ImageField(upload_to='images/blogs/'),
        ),
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='images/slider/'),
        ),
        migrations.AlterField(
            model_name='vision',
            name='description',
            field=models.TextField(),
        ),
        migrations.RenameModel(
            old_name='Leader_says_section',
            new_name='LeaderSaysSection',
        ),
        migrations.DeleteModel(
            name='About_SWLP',
        ),
        migrations.DeleteModel(
            name='About_SWLP_icons',
        ),
        migrations.DeleteModel(
            name='All_events',
        ),
        migrations.DeleteModel(
            name='Children_events',
        ),
        migrations.DeleteModel(
            name='Elderly_events',
        ),
        migrations.DeleteModel(
            name='Empowerment_events',
        ),
        migrations.DeleteModel(
            name='Environment_events',
        ),
        migrations.DeleteModel(
            name='Health_events',
        ),
        migrations.DeleteModel(
            name='Leader_says',
        ),
        migrations.DeleteModel(
            name='Our_childrens',
        ),
        migrations.DeleteModel(
            name='Our_childrens_section',
        ),
        migrations.DeleteModel(
            name='Vision_icons',
        ),
        migrations.AddField(
            model_name='visionicons',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Vision'),
        ),
        migrations.AddField(
            model_name='ourchildrens',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.OurChildrensSection'),
        ),
        migrations.AddField(
            model_name='leadersays',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.LeaderSaysSection'),
        ),
        migrations.AddField(
            model_name='healthevents',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Events'),
        ),
        migrations.AddField(
            model_name='environmentevents',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Events'),
        ),
        migrations.AddField(
            model_name='empowermentevents',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Events'),
        ),
        migrations.AddField(
            model_name='elderlyevents',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Events'),
        ),
        migrations.AddField(
            model_name='childrenevents',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Events'),
        ),
        migrations.AddField(
            model_name='allevents',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Events'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.BlogSection'),
        ),
        migrations.DeleteModel(
            name='Blog_section',
        ),
    ]
