# Generated by Django 3.0.5 on 2020-04-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='images/gallery'),
        ),
        migrations.AlterField(
            model_name='visionicons',
            name='icon',
            field=models.ImageField(upload_to='images/vision/icons/'),
        ),
    ]
