# Generated by Django 3.0.5 on 2020-04-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200425_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutswlpicons',
            name='icon',
            field=models.CharField(max_length=50),
        ),
    ]
