# Generated by Django 3.0.5 on 2020-04-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200421_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visionicons',
            name='icon',
            field=models.CharField(max_length=20),
        ),
    ]
