# Generated by Django 3.0.5 on 2020-04-12 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200412_0849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutswlp',
            options={'verbose_name_plural': 'AboutSWLP'},
        ),
        migrations.AlterModelOptions(
            name='aboutswlpicons',
            options={'verbose_name_plural': 'AboutSWLPIcons'},
        ),
        migrations.AlterModelOptions(
            name='blogs',
            options={'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='blogsection',
            options={'verbose_name_plural': 'BlogSection'},
        ),
        migrations.AlterModelOptions(
            name='boardteam',
            options={'verbose_name_plural': 'BoardTeam'},
        ),
        migrations.AlterModelOptions(
            name='childrenevents',
            options={'verbose_name_plural': 'ChildrenEvents'},
        ),
        migrations.AlterModelOptions(
            name='elderlyevents',
            options={'verbose_name_plural': 'ElderlyEvents'},
        ),
        migrations.AlterModelOptions(
            name='empowermentevents',
            options={'verbose_name_plural': 'EmpowermentEvents'},
        ),
        migrations.AlterModelOptions(
            name='environmentevents',
            options={'verbose_name_plural': 'EnvironmentEvents'},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='healthevents',
            options={'verbose_name_plural': 'HealthEvents'},
        ),
        migrations.AlterModelOptions(
            name='joinus',
            options={'verbose_name_plural': 'JoinUs'},
        ),
        migrations.AlterModelOptions(
            name='leadersays',
            options={'verbose_name_plural': 'LeaderSays'},
        ),
        migrations.AlterModelOptions(
            name='leadersayssection',
            options={'verbose_name_plural': 'LeaderSaysSection'},
        ),
        migrations.AlterModelOptions(
            name='organizingteam',
            options={'verbose_name_plural': 'OrganizingTeam'},
        ),
        migrations.AlterModelOptions(
            name='ourchildrens',
            options={'verbose_name_plural': 'OurChildrens'},
        ),
        migrations.AlterModelOptions(
            name='ourchildrenssection',
            options={'verbose_name_plural': 'OurChildrensSection'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': 'Slider'},
        ),
        migrations.AlterModelOptions(
            name='vision',
            options={'verbose_name_plural': 'Vision'},
        ),
        migrations.AlterModelOptions(
            name='visionicons',
            options={'verbose_name_plural': 'VisionIcons'},
        ),
        migrations.RemoveField(
            model_name='slider',
            name='image',
        ),
        migrations.DeleteModel(
            name='AllEvents',
        ),
    ]
