# Generated by Django 3.0.5 on 2020-04-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200422_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visionicons',
            name='icon',
            field=models.CharField(max_length=30),
        ),
    ]
