# Generated by Django 3.0.5 on 2020-04-12 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200412_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/slider/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Slider')),
            ],
            options={
                'verbose_name_plural': 'SliderImage',
            },
        ),
    ]
