# Generated by Django 3.0.5 on 2020-04-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_blogcitations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutswlp',
            options={'verbose_name_plural': 'About SWLP'},
        ),
        migrations.AlterModelOptions(
            name='aboutswlpicons',
            options={'verbose_name_plural': 'About SWLP Icons'},
        ),
        migrations.AlterModelOptions(
            name='blogsection',
            options={'verbose_name_plural': 'Blog Section'},
        ),
        migrations.AlterModelOptions(
            name='boardteam',
            options={'verbose_name_plural': 'Board Team'},
        ),
        migrations.AlterModelOptions(
            name='joinus',
            options={'verbose_name_plural': 'Join Us'},
        ),
        migrations.AlterModelOptions(
            name='leadersays',
            options={'verbose_name_plural': 'Leaders'},
        ),
        migrations.AlterModelOptions(
            name='leadersayssection',
            options={'verbose_name_plural': 'Leaders Section'},
        ),
        migrations.AlterModelOptions(
            name='organizingteam',
            options={'verbose_name_plural': 'Organizing Team'},
        ),
        migrations.AlterModelOptions(
            name='ourchildrens',
            options={'verbose_name_plural': 'Children'},
        ),
        migrations.AlterModelOptions(
            name='ourchildrenssection',
            options={'verbose_name_plural': 'Children Section'},
        ),
        migrations.AlterModelOptions(
            name='visionicons',
            options={'verbose_name_plural': 'Vision Icons'},
        ),
        migrations.RemoveField(
            model_name='aboutswlpicons',
            name='image_alt_txt',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='image_alt_txt',
        ),
        migrations.RemoveField(
            model_name='boardteam',
            name='image_alt_txt',
        ),
        migrations.RemoveField(
            model_name='leadersays',
            name='image_alt_txt',
        ),
        migrations.RemoveField(
            model_name='organizingteam',
            name='image_alt_txt',
        ),
        migrations.RemoveField(
            model_name='ourcauses',
            name='image_alt_txt',
        ),
        migrations.RemoveField(
            model_name='ourchildrens',
            name='image_alt_txt',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='image_alt_txt',
        ),
        migrations.AddField(
            model_name='boardteam',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogs',
            name='content',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='heading',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='summary',
            field=models.TextField(max_length=150),
        ),
    ]
