# Generated by Django 3.0.5 on 2020-04-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200422_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='button_text',
        ),
        migrations.AddField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/slider/'),
        ),
    ]
