# Generated by Django 3.0.5 on 2020-04-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_sliderimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimage',
            name='image',
            field=models.ImageField(upload_to='.images/slider/'),
        ),
    ]
