# Generated by Django 3.0.5 on 2020-04-22 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200422_1414'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SliderImage',
        ),
    ]
