# Generated by Django 3.0.5 on 2020-04-13 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200412_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/events/all/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Events')),
            ],
            options={
                'verbose_name_plural': 'AllEvents',
            },
        ),
    ]
