# Generated by Django 3.0.5 on 2020-04-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_delete_sliderimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(default='', upload_to='images/slider/'),
        ),
    ]
