# Generated by Django 3.0.5 on 2020-05-02 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200502_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcitations',
            options={'verbose_name_plural': 'BlogCitations'},
        ),
    ]
