# Generated by Django 3.0.5 on 2020-04-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200422_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vision',
            name='less',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='vision',
            name='more',
            field=models.TextField(default=''),
        ),
    ]
