# Generated by Django 3.0.5 on 2020-04-15 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_allevents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimage',
            name='section',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='website.Slider'),
        ),
    ]
