# Generated by Django 3.0.5 on 2020-05-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200502_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizingteam',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
