# Generated by Django 3.0.5 on 2020-05-02 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20200502_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=12)),
                ('date_of_birth', models.CharField(max_length=20)),
                ('city_or_town', models.CharField(max_length=50)),
                ('state_or_region', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('are_you_currently_working', models.CharField(max_length=20)),
                ('have_you_been_a_social_worker_before', models.CharField(max_length=100)),
                ('academic_qualifications', models.CharField(max_length=50)),
                ('permanent_address', models.TextField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('language_known', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why_be_a_fellow_content', models.TextField()),
                ('about_the_fellowship_content', models.TextField()),
                ('the_pre_eminent_will_be_awarded_content', models.TextField()),
                ('eligibility_content', models.TextField()),
                ('selection_Process_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FormQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=300)),
                ('answer', models.TextField(blank=True)),
                ('application_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.ApplicationForm')),
            ],
        ),
    ]
