# Generated by Django 3.0.5 on 2020-05-02 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_applicationform_formquestions_programs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormQuestions',
            new_name='ApplicationFormQuestions',
        ),
    ]
