# Generated by Django 3.0.5 on 2020-04-19 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20200415_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allevents',
            name='section',
        ),
        migrations.AddField(
            model_name='allevents',
            name='tag',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visionicons',
            name='icon',
            field=models.CharField(max_length=20),
        ),
    ]
