# Generated by Django 3.0.5 on 2020-04-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20200423_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='role',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='section',
        ),
        migrations.AddField(
            model_name='blogs',
            name='heading',
            field=models.CharField(default='Blog Heading goes here', max_length=100),
        ),
        migrations.AddField(
            model_name='blogs',
            name='summary',
            field=models.TextField(default='Blog Summary goes here'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='content',
            field=models.TextField(default='Blog Content goes here'),
        ),
    ]
