# Generated by Django 3.0.5 on 2020-04-19 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20200419_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allevents',
            name='tag',
        ),
        migrations.AddField(
            model_name='allevents',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.Events'),
            preserve_default=False,
        ),
    ]
