# Generated by Django 3.0.5 on 2020-05-02 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20200502_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationformquestions',
            name='application_form',
        ),
    ]
