# Generated by Django 3.0.5 on 2020-04-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20200419_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vision',
            old_name='description',
            new_name='less',
        ),
        migrations.AddField(
            model_name='vision',
            name='more',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
