# Generated by Django 3.0.5 on 2020-05-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_remove_applicationformquestions_application_form'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationFormQuestions',
        ),
        migrations.AddField(
            model_name='applicationform',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='reference',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationform',
            name='when_can_you_start',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
