# Generated by Django 3.0.5 on 2020-04-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20200419_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/events/all/')),
                ('heading', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Gallery',
            },
        ),
        migrations.CreateModel(
            name='OurCauses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/our_causes')),
            ],
        ),
        migrations.RemoveField(
            model_name='childrenevents',
            name='section',
        ),
        migrations.RemoveField(
            model_name='elderlyevents',
            name='section',
        ),
        migrations.RemoveField(
            model_name='empowermentevents',
            name='section',
        ),
        migrations.RemoveField(
            model_name='environmentevents',
            name='section',
        ),
        migrations.RemoveField(
            model_name='healthevents',
            name='section',
        ),
        migrations.DeleteModel(
            name='AllEvents',
        ),
        migrations.DeleteModel(
            name='ChildrenEvents',
        ),
        migrations.DeleteModel(
            name='ElderlyEvents',
        ),
        migrations.DeleteModel(
            name='EmpowermentEvents',
        ),
        migrations.DeleteModel(
            name='EnvironmentEvents',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='HealthEvents',
        ),
    ]
