# Generated by Django 3.0.5 on 2020-04-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20200424_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='content',
            field=models.TextField(default='Blog Content goes here', max_length=5000),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='summary',
            field=models.TextField(default='Blog Summary goes here', max_length=150),
        ),
    ]
