# Generated by Django 3.0.5 on 2020-05-03 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20200502_1900'),
        ('website', '0008_organizingteam_url'),
    ]

    operations = [
    ]
