# Generated by Django 3.0.5 on 2020-04-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20200424_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutswlp',
            name='image_alt_txt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aboutswlpicons',
            name='image_alt_txt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='blogs',
            name='image_alt_txt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='boardteam',
            name='image_alt_txt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image_alt_txt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='leadersays',
            name='image_alt_txt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organizingteam',
            name='image_alt_txt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ourcauses',
            name='image_alt_txt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ourchildrens',
            name='image_alt_txt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='slider',
            name='image_alt_txt',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
