# Generated by Django 3.0.5 on 2020-04-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20200420_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='heading',
        ),
        migrations.AddField(
            model_name='gallery',
            name='tag',
            field=models.CharField(default='all', max_length=20),
            preserve_default=False,
        ),
    ]
