# Generated by Django 3.0.5 on 2020-04-20 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20200420_1438'),
        ('website', '0013_auto_20200420_0858'),
    ]

    operations = [
    ]
