# Generated by Django 3.0.5 on 2020-04-21 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20200420_0858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='role',
            new_name='author',
        ),
    ]
