# Generated by Django 3.0.5 on 2020-05-04 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_merge_20200503_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationform',
            options={'verbose_name_plural': 'ApplicationForms'},
        ),
    ]
