# Generated by Django 3.0.5 on 2020-04-21 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20200421_0438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='name',
            new_name='role',
        ),
    ]
