# Generated by Django 3.0.5 on 2020-05-04 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20200504_1700'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicationForm',
            new_name='ApplicationForms',
        ),
    ]
