# Generated by Django 3.0.5 on 2020-04-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20200421_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vision',
            name='description',
        ),
        migrations.AddField(
            model_name='vision',
            name='less',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vision',
            name='more',
            field=models.TextField(null=True),
        ),
    ]
