# Generated by Django 3.0.5 on 2020-05-05 13:34

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_a'),
    ]

    operations = [
        migrations.DeleteModel(
            name='A',
        ),
        migrations.DeleteModel(
            name='ApplicationForms',
        ),
        migrations.RemoveField(
            model_name='programs',
            name='about_the_fellowship_content',
        ),
        migrations.RemoveField(
            model_name='programs',
            name='eligibility_content',
        ),
        migrations.RemoveField(
            model_name='programs',
            name='selection_Process_content',
        ),
        migrations.RemoveField(
            model_name='programs',
            name='the_pre_eminent_will_be_awarded_content',
        ),
        migrations.RemoveField(
            model_name='programs',
            name='why_be_a_fellow_content',
        ),
        migrations.AddField(
            model_name='programs',
            name='content',
            field=djrichtextfield.models.RichTextField(default=0),
            preserve_default=False,
        ),
    ]
