# Generated by Django 3.0.5 on 2020-05-08 02:44

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20200505_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/donate/')),
                ('content', djrichtextfield.models.RichTextField()),
            ],
        ),
    ]
