# Generated by Django 3.0.5 on 2020-05-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_donate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programs',
            options={'verbose_name_plural': 'Programs'},
        ),
        migrations.AddField(
            model_name='programs',
            name='heading',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programs',
            name='image',
            field=models.ImageField(default=None, upload_to='images/blogs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programs',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
    ]
