# Generated by Django 3.0.5 on 2020-05-10 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20200509_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donate',
            name='content',
        ),
    ]
