# Generated by Django 3.0.5 on 2020-05-14 14:01

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_campaign_compaign_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'verbose_name_plural': 'Campaign'},
        ),
        migrations.AddField(
            model_name='campaign',
            name='button_text',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='description',
            field=djrichtextfield.models.RichTextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='heading_on_image',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
