# Generated by Django 3.0.5 on 2020-05-14 14:12

from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20200514_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='content',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='heading',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='image',
            field=models.ImageField(upload_to='images/campaign/'),
        ),
        migrations.CreateModel(
            name='CampaignBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/campaign')),
                ('content', djrichtextfield.models.RichTextField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Campaign')),
            ],
            options={
                'verbose_name_plural': 'CampaignBlog',
            },
        ),
    ]
