# Generated by Django 3.0.5 on 2020-05-14 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_auto_20200514_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='heading_on_image',
            new_name='text_on_image',
        ),
    ]
