# Generated by Django 3.0.5 on 2020-05-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_auto_20200516_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='button_text',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='text_on_image',
            field=models.CharField(max_length=50),
        ),
    ]
