# Generated by Django 3.0.5 on 2020-05-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_auto_20200516_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='text_on_image',
            field=models.CharField(max_length=150),
        ),
    ]
