# Generated by Django 3.0.5 on 2020-05-20 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_auto_20200516_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fellowship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_image', models.ImageField(upload_to='images/fellowship/header/')),
            ],
        ),
        migrations.CreateModel(
            name='FellowshipImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/fellowship/')),
                ('fellowship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Fellowship')),
            ],
        ),
        migrations.CreateModel(
            name='FellowSays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/fellowship/fellow_says')),
                ('content', models.TextField()),
                ('fellowship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Fellowship')),
            ],
        ),
    ]
