# Generated by Django 3.0.5 on 2020-05-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_fellowsays_fellowship_fellowshipimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fellowsays',
            options={'verbose_name_plural': 'Fellow Says'},
        ),
        migrations.AlterModelOptions(
            name='fellowshipimages',
            options={'verbose_name_plural': 'Images'},
        ),
        migrations.AlterField(
            model_name='fellowshipimages',
            name='image',
            field=models.ImageField(upload_to='images/fellowship/'),
        ),
    ]
