# Generated by Django 3.0.7 on 2020-06-18 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_auto_20200522_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vision',
            old_name='less',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='joinus',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='vision',
            name='more',
        ),
    ]
