# Generated by Django 3.0.7 on 2020-06-22 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_auto_20200618_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visionicons',
            name='icon_description',
        ),
    ]
