# Generated by Django 3.0.5 on 2020-06-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_remove_fellowshipapplicationform_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fellowshipapplicationform',
            name='academic_qualification',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fellowshipapplicationform',
            name='are_you_currently_working',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fellowshipapplicationform',
            name='city',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fellowshipapplicationform',
            name='define_leadership',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fellowshipapplicationform',
            name='email',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fellowshipapplicationform',
            name='explain_how_you_are_going_to_be_empathetic_with_the_child_who_are_divergent',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fellowshipapplicationform',
            name='full_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fellowshipapplicationform',
            name='have_you_been_a_social_worker_before',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fellowshipapplicationform',
            name='how_can_you_change_the_perspective_of_a_chld_who_think_educartion_is_worthless',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fellowshipapplicationform',
            name='how_do_you_plan_on_building_a_healthy_relationship_with_the_students',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fellowshipapplicationform',
            name='if_yes_please_mention_the_organisation',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fellowshipapplicationform',
            name='language_known',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fellowshipapplicationform',
            name='mobile_no',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fellowshipapplicationform',
            name='permanent_address',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fellowshipapplicationform',
            name='references',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fellowshipapplicationform',
            name='sex',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fellowshipapplicationform',
            name='what_are_your_strength_and_weakness_as_a_social_worker',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fellowshipapplicationform',
            name='what_motivates_you_to_selfilessly_work_for_us_without_pay',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fellowshipapplicationform',
            name='when_you_start',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fellowshipapplicationform',
            name='why_do_you_think_education_is_important',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fellowshipapplicationform',
            name='why_do_you_want_to_be_a_fellow',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
