# Generated by Django 3.0.7 on 2020-06-22 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_remove_visionicons_icon_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardteam',
            name='description',
        ),
    ]
