# Generated by Django 3.0.5 on 2020-06-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_auto_20200601_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='fellowshipapplicationform',
            name='d_o_b',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
