# Generated by Django 3.0.7 on 2020-08-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_remove_boardteam_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donate',
        ),
        migrations.AddField(
            model_name='joinus',
            name='button_text',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
