# Generated by Django 3.0.5 on 2020-06-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_fellowshipapplicationform_d_o_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='fellowshipapplicationform',
            name='if_yes_please_mention_the_organisations',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fellowshipapplicationform',
            name='state',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
