# Generated by Django 3.0.7 on 2020-08-09 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_auto_20200809_1534'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogCitations',
        ),
    ]
