# Generated by Django 3.0.7 on 2020-09-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='online',
            name='image',
            field=models.ImageField(upload_to='images/teachers/'),
        ),
    ]
