# Generated by Django 3.0.7 on 2020-09-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_auto_20200924_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='online',
            name='image',
            field=models.ImageField(upload_to='images/online/'),
        ),
    ]
